In [2]:
import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Prabhu\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Prabhu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
df = pd.read_csv("imdb_movies_2024.csv")
df.head()

,Movie Name,Storyline,Cleaned_Storyline
0,The Substance,A fading celebrity takes a black-market drug: ...,fading celebrity takes blackmarket drug cellre...
1,The Life of Chuck,"A life-affirming, genre-bending story about th...",lifeaffirming genrebending story three chapter...
2,Bone Lake,A couple's vacation at a secluded estate is up...,couples vacation secluded estate upended theyr...
3,Anora,A young stripper from Brooklyn meets and impul...,young stripper brooklyn meets impulsively marr...
4,Eden,Based on a factual account of a group of outsi...,based factual account group outsiders settle r...

In [5]:
df.shape

(5099, 3)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Movie Name         5099 non-null   object
 1   Storyline          5099 non-null   object
 2   Cleaned_Storyline  5099 non-null   object
dtypes: object(3)
memory usage: 119.6+ KB

In [7]:
df

,Movie Name,Storyline,Cleaned_Storyline
0,The Substance,A fading celebrity takes a black-market drug: ...,fading celebrity takes blackmarket drug cellre...
1,The Life of Chuck,"A life-affirming, genre-bending story about th...",lifeaffirming genrebending story three chapter...
2,Bone Lake,A couple's vacation at a secluded estate is up...,couples vacation secluded estate upended theyr...
3,Anora,A young stripper from Brooklyn meets and impul...,young stripper brooklyn meets impulsively marr...
4,Eden,Based on a factual account of a group of outsi...,based factual account group outsiders settle r...
...,...,...,...
5094,Juni,Partha is a young chef in Bangalore who falls ...,partha young chef bangalore falls juni regular...
5095,Timing,Two young ex-lovers randomly reconnect.,two young exlovers randomly reconnect
5096,Lakatabu,When a man begins to use his powers for crimin...,man begins use powers criminal activities thre...
5097,Emakku Thozhil Romance,Assistant director Umashankar falls for Leo. M...,assistant director umashankar falls leo misund...
5098,Crush,A young woman takes her unusual obsession for ...,young woman takes unusual obsession married ma...

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.duplicated(subset=["Movie Name"]).sum()

np.int64(40)

In [10]:
df.duplicated(subset=["Movie Name"]).sum()

np.int64(40)

In [11]:
df[df.duplicated(subset=["Movie Name"], keep=False)]

,Movie Name,Storyline,Cleaned_Storyline
7,Civil War,"In a dystopian future, four journalists travel...",dystopian future four journalists travel acros...
8,He's Watching You,A teenager investigating mysterious murders in...,teenager investigating mysterious murders smal...
77,Elevation,A single father and two women venture from the...,single father two women venture safety homes f...
122,Strangers,A frustrated woman encounters a mysterious hit...,frustrated woman encounters mysterious hitman ...
197,A Sacrifice,American social psychologist Ben Monroe invest...,american social psychologist ben monroe invest...
...,...,...,...
4667,Teacher's Pet,When a dog wants to be a boy after watching Pi...,dog wants boy watching pinocchio meets mad sci...
4761,The Premiere,A painfully narcissistic theater producer atte...,painfully narcissistic theater producer attemp...
4846,Touch,"TOUCH follows a young man, Ben, who gets trapp...",touch follows young man ben gets trapped consc...
4870,The Promise,"While trapped in her car miles away, Maja must...",trapped car miles away maja must overcome fear...
4957,Exit,A group of students travel to a mysterious car...,group students travel mysterious carnival fun ...

In [12]:
df["Movie Name"].value_counts()[df["Movie Name"].value_counts() > 1]

Movie Name
Touch                    3
Rita                     3
Marco                    2
Strangers                2
Audrey                   2
Kali                     2
The Kingdom              2
Elevation                2
Occupied                 2
The Promise              2
Checkmate                2
Three                    2
Exit                     2
A Family Affair          2
Unspoken                 2
Tenant                   2
Succubus                 2
The One That Got Away    2
Inheritance              2
Sunlight                 2
Nyctophobia              2
Teacher's Pet            2
The Other Side           2
A Sacrifice              2
The Contract             2
Till Death Do Us Part    2
Game On                  2
Escape                   2
Blink                    2
Breathe                  2
Pepe                     2
Blue                     2
The Damned               2
Throuple                 2
The Premiere             2
Aftermath                2
Civil War                2
He's Watching You        2
Name: count, dtype: int64

In [13]:
df = df.drop_duplicates(subset=["Movie Name"]).reset_index(drop=True)

In [14]:
df

,Movie Name,Storyline,Cleaned_Storyline
0,The Substance,A fading celebrity takes a black-market drug: ...,fading celebrity takes blackmarket drug cellre...
1,The Life of Chuck,"A life-affirming, genre-bending story about th...",lifeaffirming genrebending story three chapter...
2,Bone Lake,A couple's vacation at a secluded estate is up...,couples vacation secluded estate upended theyr...
3,Anora,A young stripper from Brooklyn meets and impul...,young stripper brooklyn meets impulsively marr...
4,Eden,Based on a factual account of a group of outsi...,based factual account group outsiders settle r...
...,...,...,...
5054,Juni,Partha is a young chef in Bangalore who falls ...,partha young chef bangalore falls juni regular...
5055,Timing,Two young ex-lovers randomly reconnect.,two young exlovers randomly reconnect
5056,Lakatabu,When a man begins to use his powers for crimin...,man begins use powers criminal activities thre...
5057,Emakku Thozhil Romance,Assistant director Umashankar falls for Leo. M...,assistant director umashankar falls leo misund...
5058,Crush,A young woman takes her unusual obsession for ...,young woman takes unusual obsession married ma...

In [15]:
stop_words = set(stopwords.words("english"))

In [16]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z\s]", "", text)
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    return " ".join(tokens)

In [17]:
from nltk.stem import WordNetLemmatizer

In [18]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Prabhu\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [31]:
lemmatizer = WordNetLemmatizer()

In [32]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z\s]", "", text)

    tokens = word_tokenize(text)

    # remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # ✅ LEMMATIZATION HAPPENS HERE
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

In [33]:
df["clean_story"] = df["Storyline"].apply(clean_text)

df[["Movie Name", "Storyline", "clean_story"]].head()

,Movie Name,Storyline,clean_story
0,The Substance,A fading celebrity takes a black-market drug: ...,fading celebrity take blackmarket drug cellrep...
1,The Life of Chuck,"A life-affirming, genre-bending story about th...",lifeaffirming genrebending story three chapter...
2,Bone Lake,A couple's vacation at a secluded estate is up...,couple vacation secluded estate upended theyre...
3,Anora,A young stripper from Brooklyn meets and impul...,young stripper brooklyn meet impulsively marri...
4,Eden,Based on a factual account of a group of outsi...,based factual account group outsider settle re...

In [34]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df["clean_story"])

In [35]:
print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 91561 stored elements and shape (5059, 16241)>
  Coords	Values
  (0, 4981)	0.3255138998606177
  (0, 2220)	0.2842500242460734
  (0, 14227)	0.1610740096396994
  (0, 1550)	0.3717329544911883
  (0, 4146)	0.23230383505949476
  (0, 2232)	0.3717329544911883
  (0, 13918)	0.3546748766089894
  (0, 6366)	0.18844448653278265
  (0, 3134)	0.25379447161532537
  (0, 16133)	0.26898244621916284
  (0, 1446)	0.2578042086742164
  (0, 15472)	0.3040232633047871
  (1, 8221)	0.4110225945354089
  (1, 5702)	0.3921615940666041
  (1, 13807)	0.1698513418611133
  (1, 14529)	0.20866092997704783
  (1, 2301)	0.3276754075313903
  (1, 8220)	0.12836258530228364
  (1, 10213)	0.3142933147325882
  (1, 8672)	0.1689480717174432
  (1, 9586)	0.24563864382410028
  (1, 2313)	0.3527478812158372
  (1, 7913)	0.4110225945354089
  (2, 3074)	0.3009365024535784
  (2, 15345)	0.20661281720592534
  :	:
  (5057, 5002)	0.13344777842830804
  (5057, 3830)	0.17015162603828077
  (5057, 11079)	0.18166924766999273
  (5057, 930)	0.1972881810718717
  (5057, 809)	0.2196759824380677
  (5057, 1563)	0.22720578578103173
  (5057, 9252)	0.22320496046649424
  (5057, 8160)	0.4464099209329885
  (5057, 12166)	0.243972816864745
  (5057, 15034)	0.5294813465259914
  (5057, 12569)	0.2647406732629957
  (5057, 11048)	0.2647406732629957
  (5058, 14227)	0.1926060217674397
  (5058, 8672)	0.18271028612547105
  (5058, 16132)	0.1717064086582138
  (5058, 15927)	0.17305699018263382
  (5058, 5513)	0.2608532508251457
  (5058, 10023)	0.32866960762914543
  (5058, 13857)	0.31174298811882845
  (5058, 8798)	0.25893048913423494
  (5058, 15850)	0.22664129754577955
  (5058, 15259)	0.3194977138308048
  (5058, 9799)	0.2825745576035949
  (5058, 8186)	0.35874447960846845
  (5058, 10009)	0.4096342169021513

In [36]:
similarity_matrix = cosine_similarity(tfidf_matrix)

In [38]:
def recommend_from_storyline(user_story, top_n=5):
    
    # Clean user input
    user_clean = clean_text(user_story)
    user_vector = vectorizer.transform([user_clean])
    
    # Compute similarity
    similarity_scores = cosine_similarity(user_vector, tfidf_matrix)[0]
    
    # Sort indices by similarity
    sorted_indices = similarity_scores.argsort()[::-1]
    
    seen = set()
    recommendations = []
    
    for idx in sorted_indices:
        movie_name = df.iloc[idx]["Movie Name"]
        
        if movie_name not in seen:
            seen.add(movie_name)
            
            recommendations.append({
                "Movie Name": movie_name,
                "Storyline": df.iloc[idx]["Storyline"],
                "Similarity Score": round(similarity_scores[idx], 3)
            })
        
        if len(recommendations) == top_n:
            break
    
    return recommendations

In [39]:
test_story = """
A warrior leads a rebellion in a futuristic world to save humanity
from powerful enemies and survive a deadly war.
"""

In [40]:
results = recommend_from_storyline(test_story, top_n=5)

for i, movie in enumerate(results, 1):
    print(f"\n{i}. {movie['Movie Name']}")
    print(f"   Similarity Score: {movie['Similarity Score']}")
    print(f"   Storyline: {movie['Storyline']}")

1. Monster Island
   Similarity Score: 0.205
   Storyline: Set in the Pacific, 1942. A Japanese soldier and a British prisoner of war are stranded on a deserted island, hunted by a deadly creature. Two mortal enemies must come together to survive the unknown.

2. Rebel Moon - Part Two: The Scargiver
   Similarity Score: 0.203
   Storyline: Kora and surviving warriors prepare to defend Veldt, their new home, alongside its people against the Realm. The warriors face their pasts, revealing their motivations before the Realm's forces arrive to crush the growing rebellion.

3. Cora
   Similarity Score: 0.192
   Storyline: After a deadly mist has wiped out most of humanity, a mysterious organisation is trying to save what's left of humankind.

4. Can You Hear Me?
   Similarity Score: 0.175
   Storyline: A World War 1 Romantic Ghost Story

5. Atlas
   Similarity Score: 0.166
   Storyline: In a bleak-sounding future, an A.I. soldier has determined that the only way to end war is to end humanity.

In [41]:
pd.DataFrame(results)

,Movie Name,Storyline,Similarity Score
0,Monster Island,"Set in the Pacific, 1942. A Japanese soldier a...",0.205
1,Rebel Moon - Part Two: The Scargiver,Kora and surviving warriors prepare to defend ...,0.203
2,Cora,After a deadly mist has wiped out most of huma...,0.192
3,Can You Hear Me?,A World War 1 Romantic Ghost Story,0.175
4,Atlas,"In a bleak-sounding future, an A.I. soldier ha...",0.166

In [42]:
df

,Movie Name,Storyline,clean_story
0,The Substance,A fading celebrity takes a black-market drug: ...,fading celebrity take blackmarket drug cellrep...
1,The Life of Chuck,"A life-affirming, genre-bending story about th...",lifeaffirming genrebending story three chapter...
2,Bone Lake,A couple's vacation at a secluded estate is up...,couple vacation secluded estate upended theyre...
3,Anora,A young stripper from Brooklyn meets and impul...,young stripper brooklyn meet impulsively marri...
4,Eden,Based on a factual account of a group of outsi...,based factual account group outsider settle re...
...,...,...,...
5054,Juni,Partha is a young chef in Bangalore who falls ...,partha young chef bangalore fall juni regular ...
5055,Timing,Two young ex-lovers randomly reconnect.,two young exlovers randomly reconnect
5056,Lakatabu,When a man begins to use his powers for crimin...,man begin use power criminal activity threaten...
5057,Emakku Thozhil Romance,Assistant director Umashankar falls for Leo. M...,assistant director umashankar fall leo misunde...
5058,Crush,A young woman takes her unusual obsession for ...,young woman take unusual obsession married man...

In [43]:
# After preprocessing
df.to_csv("imdb_cleaned.csv", index=False)